version: 1

before:
  hooks:
    - go mod tidy

builds:
  - main: "./main.go"
    ldflags:
      - -s -w -X "main.goversion={{.Env.GO_VERSION}}"
      - -s -w -X "main.goinitversion={{.Env.GIT_TAG}}"
    binary: goinit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
